### Get Hello World
GET http://localhost:3000

### Create an Account
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "silly.user@email.com",
  "password": "secret_\\>:3"
}

### Login as User
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "silly.user@email.com",
  "password": "secret_\\>:3"
}

### Update User
PUT http://localhost:3000/auth/update
Content-Type: application/json

{
  "id": "c0f77128-c5e3-423e-978b-45b53f2676e6",
  "email": "silly.user@email.com",
  "password": "secret_\\>:3"
}

### Delete User
DELETE http://localhost:3000/auth/delete
Content-Type: application/json

{
  "id": "c0f77128-c5e3-423e-978b-45b53f2676e6",
  "password": "secret_\\>:3"
}
