### Get Hello World
GET http://localhost:3000

### Create an Account
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "silly.user@email.com",
  "password": "secret_\\>:3"
}

### Login as User
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "silly.user@email.com",
  "password": "secret_\\>:3"
}

### Update User
PUT http://localhost:3000/auth/update
Content-Type: application/json

{
  "id": "c0f77128-c5e3-423e-978b-45b53f2676e6",
  "email": "silly.user@email.com",
  "password": "secret_\\>:3"
}

### Delete User
DELETE http://localhost:3000/auth/delete
Content-Type: application/json

{
  "id": "c0f77128-c5e3-423e-978b-45b53f2676e6",
  "password": "secret_\\>:3"
}

### Get Profile
GET http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4OTM1MTc4OS1hYzQ5LTQyNjMtOWJmZi0xOGFjOWY5OGRhZTkiLCJlbWFpbCI6InNpbGx5LnVzZXJAZW1haWwuY29tIiwiaWF0IjoxNzcxODkxOTUwLCJleHAiOjE3NzE4OTI4NTB9.u4nDBpzu2AeYBpTpEXIj7tWl5kg8jHy3rSimybxGwn0
